package frc.robot.utility.Shooter;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import frc.robot.Constants.HoodConstants;
import frc.robot.Constants.ShooterConstants;
import frc.robot.Constants.ShotModelConstants;

/**
 * Solves a hub shot from the calibrated drag and Magnus model used by the shot-calibrator app.
 * All angles returned to robot code use the hood's rear-referenced command convention.
 */
public final class PhysicsShotSolver {
    public record Solution(
        double targetDistanceMeters,
        double flywheelRPM,
        double hoodCommandDegrees,
        double launchElevationDegrees,
        double timeOfFlightSeconds,
        double entryAngleDegrees,
        double crossingXMeters,
        double openingClearanceMeters,
        double nearRimClearanceMeters,
        double robustnessRadius,
        double rpmToleranceLower,
        double rpmToleranceUpper,
        double hoodToleranceLowerDegrees,
        double hoodToleranceUpperDegrees,
        boolean valid
    ) {}

    private record EntryMetrics(
        double timeSeconds,
        double entryAngleDegrees,
        double crossingXMeters,
        double centerOffsetMeters,
        double openingClearanceMeters,
        double nearRimClearanceMeters,
        boolean inside,
        boolean scoring
    ) {}

    private record Candidate(int hoodIndex, int rpmIndex, double robustness, double objective) {}

    private static final int HOOD_STEPS = 29;
    private static final int RPM_STEPS = 41;
    private static final double GRID_DT_SECONDS = 0.012;
    private static final double REFINEMENT_DT_SECONDS = 0.004;
    private static final double MAX_TIME_SECONDS = 3.0;
    private static final double CACHE_RESOLUTION_METERS = 0.025;
    private static final int MAX_CACHE_ENTRIES = 192;

    private static final double BALL_RADIUS_METERS = ShotModelConstants.BALL_DIAMETER_METERS / 2.0;
    private static final double BALL_AREA_SQUARE_METERS = Math.PI * BALL_RADIUS_METERS * BALL_RADIUS_METERS;
    private static final double DYNAMIC_ACCELERATION_FACTOR =
        0.5
            * ShotModelConstants.AIR_DENSITY_KG_PER_CUBIC_METER
            * BALL_AREA_SQUARE_METERS
            / ShotModelConstants.BALL_MASS_KG;

    private final Map<Long, Solution> solutionCache = new LinkedHashMap<>(32, 0.75f, true) {
        @Override
        protected boolean removeEldestEntry(Map.Entry<Long, Solution> eldest) {
            return size() > MAX_CACHE_ENTRIES;
        }
    };

    /**
     * Returns the robust scoring command nearest this range. The expensive command-space scan is
     * cached in 2.5 cm range bins, then the selected command is validated at the exact range.
     */
    public synchronized Solution solve(double distanceMeters) {
        if (!Double.isFinite(distanceMeters) || distanceMeters <= 0.0) {
            return invalidSolution(distanceMeters);
        }

        long cacheKey = Math.round(distanceMeters / CACHE_RESOLUTION_METERS);
        double cachedDistanceMeters = cacheKey * CACHE_RESOLUTION_METERS;
        Solution cached = solutionCache.computeIfAbsent(cacheKey, ignored -> solveGrid(cachedDistanceMeters));
        if (!cached.valid()) {
            return cached;
        }

        EntryMetrics exactMetrics = simulate(
            cached.flywheelRPM(),
            cached.hoodCommandDegrees(),
            distanceMeters,
            REFINEMENT_DT_SECONDS
        );
        if (exactMetrics != null && exactMetrics.scoring()) {
            return solutionWithMetrics(cached, distanceMeters, exactMetrics);
        }

        // A range-bin boundary can place a robust command just outside the exact scoring region.
        // Resolve that uncommon case at the requested distance instead of returning a false hit.
        return solveGrid(distanceMeters);
    }

    /**
     * Constant-time robot-loop policy generated by {@link #solve(double)} over the full range.
     * The returned command is re-simulated here, so flight time and validity still come directly
     * from the drag/Magnus equation rather than from another fitted curve.
     */
    public Solution solveRuntime(double distanceMeters) {
        if (!Double.isFinite(distanceMeters) || distanceMeters <= 0.0) {
            return invalidSolution(distanceMeters);
        }
        double rpm = evaluateQuadratic(
            ShotModelConstants.RPM_POLICY_DISTANCE_SQUARED,
            ShotModelConstants.RPM_POLICY_DISTANCE,
            ShotModelConstants.RPM_POLICY_CONSTANT,
            distanceMeters
        );
        double hoodCommand = evaluateQuadratic(
            ShotModelConstants.HOOD_POLICY_DISTANCE_SQUARED,
            ShotModelConstants.HOOD_POLICY_DISTANCE,
            ShotModelConstants.HOOD_POLICY_CONSTANT,
            distanceMeters
        );
        rpm = clamp(rpm, ShooterConstants.FLYWHEEL_IDLE_RPM, ShooterConstants.MAX_RPM);
        hoodCommand = clamp(hoodCommand, HoodConstants.HOOD_MIN_ANGLE, HoodConstants.HOOD_MAX_ANGLE);
        return evaluate(distanceMeters, rpm, hoodCommand);
    }

    public static double launchElevationDegrees(double hoodCommandDegrees) {
        return 90.0 - hoodCommandDegrees + ShotModelConstants.HOOD_OFFSET_DEGREES;
    }

    /** Evaluates one command with the full equation without scanning the command space. */
    public Solution evaluate(double distanceMeters, double flywheelRPM, double hoodCommandDegrees) {
        boolean controlsInRange = flywheelRPM >= ShooterConstants.FLYWHEEL_IDLE_RPM
            && flywheelRPM <= ShooterConstants.MAX_RPM
            && hoodCommandDegrees >= HoodConstants.HOOD_MIN_ANGLE
            && hoodCommandDegrees <= HoodConstants.HOOD_MAX_ANGLE;
        if (!Double.isFinite(distanceMeters)
                || !Double.isFinite(flywheelRPM)
                || !Double.isFinite(hoodCommandDegrees)
                || distanceMeters <= 0.0
                || !controlsInRange) {
            return invalidSolution(distanceMeters);
        }

        EntryMetrics metrics = simulate(
            flywheelRPM,
            hoodCommandDegrees,
            distanceMeters,
            REFINEMENT_DT_SECONDS
        );
        if (metrics == null) {
            return commandSolutionWithoutEntry(distanceMeters, flywheelRPM, hoodCommandDegrees);
        }
        return new Solution(
            distanceMeters,
            flywheelRPM,
            hoodCommandDegrees,
            launchElevationDegrees(hoodCommandDegrees),
            metrics.timeSeconds(),
            metrics.entryAngleDegrees(),
            metrics.crossingXMeters(),
            metrics.openingClearanceMeters(),
            metrics.nearRimClearanceMeters(),
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            metrics.scoring()
        );
    }

    private Solution solveGrid(double distanceMeters) {
        double hoodStep = (HoodConstants.HOOD_MAX_ANGLE - HoodConstants.HOOD_MIN_ANGLE) / (HOOD_STEPS - 1);
        double rpmStep = (ShooterConstants.MAX_RPM - ShooterConstants.FLYWHEEL_IDLE_RPM) / (RPM_STEPS - 1);
        boolean[][] feasible = new boolean[HOOD_STEPS][RPM_STEPS];
        double[][] objectives = new double[HOOD_STEPS][RPM_STEPS];

        for (int hoodIndex = 0; hoodIndex < HOOD_STEPS; hoodIndex++) {
            double hoodCommand = HoodConstants.HOOD_MIN_ANGLE + hoodIndex * hoodStep;
            for (int rpmIndex = 0; rpmIndex < RPM_STEPS; rpmIndex++) {
                double rpm = ShooterConstants.FLYWHEEL_IDLE_RPM + rpmIndex * rpmStep;
                EntryMetrics metrics = simulate(rpm, hoodCommand, distanceMeters, GRID_DT_SECONDS);
                if (metrics != null && metrics.scoring()) {
                    feasible[hoodIndex][rpmIndex] = true;
                    objectives[hoodIndex][rpmIndex] = objective(rpm, metrics);
                } else {
                    objectives[hoodIndex][rpmIndex] = Double.POSITIVE_INFINITY;
                }
            }
        }

        List<Candidate> candidates = new ArrayList<>();
        for (int hoodIndex = 0; hoodIndex < HOOD_STEPS; hoodIndex++) {
            for (int rpmIndex = 0; rpmIndex < RPM_STEPS; rpmIndex++) {
                if (!feasible[hoodIndex][rpmIndex]) {
                    continue;
                }
                candidates.add(new Candidate(
                    hoodIndex,
                    rpmIndex,
                    robustnessRadius(feasible, hoodIndex, rpmIndex, hoodStep, rpmStep),
                    objectives[hoodIndex][rpmIndex]
                ));
            }
        }

        candidates.sort(
            Comparator.comparingDouble(Candidate::robustness)
                .reversed()
                .thenComparingDouble(Candidate::objective)
        );

        for (Candidate candidate : candidates) {
            double hoodCommand = HoodConstants.HOOD_MIN_ANGLE + candidate.hoodIndex() * hoodStep;
            double rpm = ShooterConstants.FLYWHEEL_IDLE_RPM + candidate.rpmIndex() * rpmStep;
            EntryMetrics metrics = simulate(rpm, hoodCommand, distanceMeters, REFINEMENT_DT_SECONDS);
            if (metrics == null || !metrics.scoring()) {
                continue;
            }

            int lowerRpmIndex = candidate.rpmIndex();
            int upperRpmIndex = candidate.rpmIndex();
            while (lowerRpmIndex > 0 && feasible[candidate.hoodIndex()][lowerRpmIndex - 1]) {
                lowerRpmIndex--;
            }
            while (upperRpmIndex + 1 < RPM_STEPS && feasible[candidate.hoodIndex()][upperRpmIndex + 1]) {
                upperRpmIndex++;
            }

            int lowerHoodIndex = candidate.hoodIndex();
            int upperHoodIndex = candidate.hoodIndex();
            while (lowerHoodIndex > 0 && feasible[lowerHoodIndex - 1][candidate.rpmIndex()]) {
                lowerHoodIndex--;
            }
            while (upperHoodIndex + 1 < HOOD_STEPS && feasible[upperHoodIndex + 1][candidate.rpmIndex()]) {
                upperHoodIndex++;
            }

            return new Solution(
                distanceMeters,
                rpm,
                hoodCommand,
                launchElevationDegrees(hoodCommand),
                metrics.timeSeconds(),
                metrics.entryAngleDegrees(),
                metrics.crossingXMeters(),
                metrics.openingClearanceMeters(),
                metrics.nearRimClearanceMeters(),
                candidate.robustness(),
                (candidate.rpmIndex() - lowerRpmIndex) * rpmStep,
                (upperRpmIndex - candidate.rpmIndex()) * rpmStep,
                (candidate.hoodIndex() - lowerHoodIndex) * hoodStep,
                (upperHoodIndex - candidate.hoodIndex()) * hoodStep,
                true
            );
        }

        return invalidSolution(distanceMeters);
    }

    private static Solution solutionWithMetrics(
        Solution source,
        double distanceMeters,
        EntryMetrics metrics
    ) {
        return new Solution(
            distanceMeters,
            source.flywheelRPM(),
            source.hoodCommandDegrees(),
            source.launchElevationDegrees(),
            metrics.timeSeconds(),
            metrics.entryAngleDegrees(),
            metrics.crossingXMeters(),
            metrics.openingClearanceMeters(),
            metrics.nearRimClearanceMeters(),
            source.robustnessRadius(),
            source.rpmToleranceLower(),
            source.rpmToleranceUpper(),
            source.hoodToleranceLowerDegrees(),
            source.hoodToleranceUpperDegrees(),
            true
        );
    }

    private static Solution invalidSolution(double distanceMeters) {
        return new Solution(
            distanceMeters,
            ShooterConstants.FLYWHEEL_IDLE_RPM,
            HoodConstants.HOOD_MIN_ANGLE,
            launchElevationDegrees(HoodConstants.HOOD_MIN_ANGLE),
            Double.NaN,
            Double.NaN,
            Double.NaN,
            Double.NEGATIVE_INFINITY,
            Double.NEGATIVE_INFINITY,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            false
        );
    }

    private static Solution commandSolutionWithoutEntry(
        double distanceMeters,
        double flywheelRPM,
        double hoodCommandDegrees
    ) {
        return new Solution(
            distanceMeters,
            flywheelRPM,
            hoodCommandDegrees,
            launchElevationDegrees(hoodCommandDegrees),
            Double.NaN,
            Double.NaN,
            Double.NaN,
            Double.NEGATIVE_INFINITY,
            Double.NEGATIVE_INFINITY,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            false
        );
    }

    private static double objective(double rpm, EntryMetrics metrics) {
        double usableHalfSpan = usableHalfSpanMeters();
        double centerFraction = metrics.centerOffsetMeters() / Math.max(usableHalfSpan, 1e-6);
        double rpmFraction =
            (rpm - ShooterConstants.FLYWHEEL_IDLE_RPM)
                / Math.max(ShooterConstants.MAX_RPM - ShooterConstants.FLYWHEEL_IDLE_RPM, 1.0);
        return 0.20 * centerFraction * centerFraction
            + ShotModelConstants.FLIGHT_TIME_WEIGHT * metrics.timeSeconds() / 1.5
            + ShotModelConstants.ENTRY_ANGLE_WEIGHT
                * (1.0 - Math.min(metrics.entryAngleDegrees(), 60.0) / 60.0)
            + ShotModelConstants.MECHANISM_EFFORT_WEIGHT * rpmFraction * rpmFraction;
    }

    private static double usableHalfSpanMeters() {
        return Math.max(
            ShotModelConstants.HUB_OPENING_SPAN_METERS / 2.0
                - BALL_RADIUS_METERS
                - ShotModelConstants.HUB_RIM_MARGIN_METERS,
            0.0
        );
    }

    private static double robustnessRadius(
        boolean[][] feasible,
        int candidateHood,
        int candidateRpm,
        double hoodStep,
        double rpmStep
    ) {
        double minimumSquaredDistance = Double.POSITIVE_INFINITY;
        for (int hoodIndex = -1; hoodIndex <= HOOD_STEPS; hoodIndex++) {
            for (int rpmIndex = -1; rpmIndex <= RPM_STEPS; rpmIndex++) {
                boolean outside = hoodIndex < 0
                    || hoodIndex >= HOOD_STEPS
                    || rpmIndex < 0
                    || rpmIndex >= RPM_STEPS;
                if (!outside && feasible[hoodIndex][rpmIndex]) {
                    continue;
                }

                double hoodDistance = (candidateHood - hoodIndex) * hoodStep / 0.5;
                double rpmDistance = (candidateRpm - rpmIndex) * rpmStep / 100.0;
                minimumSquaredDistance = Math.min(
                    minimumSquaredDistance,
                    hoodDistance * hoodDistance + rpmDistance * rpmDistance
                );
            }
        }
        return Math.sqrt(minimumSquaredDistance);
    }

    private static EntryMetrics simulate(
        double topRpm,
        double hoodCommandDegrees,
        double targetDistanceMeters,
        double dtSeconds
    ) {
        double bottomRpm = topRpm * ShotModelConstants.BOTTOM_TO_TOP_RPM_RATIO;
        double topSurfaceSpeed =
            Math.PI * ShotModelConstants.TOP_WHEEL_DIAMETER_METERS * topRpm / 60.0;
        double bottomSurfaceSpeed =
            Math.PI * ShotModelConstants.BOTTOM_WHEEL_DIAMETER_METERS * bottomRpm / 60.0;
        double exitSpeed =
            ShotModelConstants.VELOCITY_TRANSFER * (topSurfaceSpeed + bottomSurfaceSpeed) / 2.0;
        double launchAngleRadians = Math.toRadians(launchElevationDegrees(hoodCommandDegrees));
        double spinRadiansPerSecond =
            ShotModelConstants.SPIN_TRANSFER
                * (bottomSurfaceSpeed - topSurfaceSpeed)
                / (2.0 * BALL_RADIUS_METERS);

        double[] state = {
            0.0,
            ShotModelConstants.RELEASE_HEIGHT_METERS,
            exitSpeed * Math.cos(launchAngleRadians),
            exitSpeed * Math.sin(launchAngleRadians),
            spinRadiansPerSecond
        };
        double[] previous = state.clone();
        double[] k1 = new double[5];
        double[] k2 = new double[5];
        double[] k3 = new double[5];
        double[] k4 = new double[5];
        double[] temporary = new double[5];

        double planeHeight = ShotModelConstants.HUB_BALL_CENTER_HEIGHT_METERS;
        double nearRimX = targetDistanceMeters - ShotModelConstants.HUB_OPENING_SPAN_METERS / 2.0;
        double nearRimHeight = Double.NaN;
        double crossingTime = Double.NaN;
        double crossingX = Double.NaN;
        double crossingVx = Double.NaN;
        double crossingVz = Double.NaN;
        double maxX = Math.max(10.0, targetDistanceMeters * 1.25);
        int steps = (int) Math.ceil(MAX_TIME_SECONDS / dtSeconds);

        for (int step = 0; step < steps; step++) {
            System.arraycopy(state, 0, previous, 0, state.length);
            rk4Step(state, dtSeconds, k1, k2, k3, k4, temporary);

            if (Double.isNaN(nearRimHeight)
                && previous[0] <= nearRimX
                && state[0] >= nearRimX
                && state[0] > previous[0]) {
                double fraction = (nearRimX - previous[0]) / (state[0] - previous[0]);
                nearRimHeight = lerp(previous[1], state[1], fraction);
            }

            if (Double.isNaN(crossingTime) && previous[1] >= planeHeight && state[1] < planeHeight) {
                double fraction = (planeHeight - previous[1]) / (state[1] - previous[1]);
                crossingTime = (step + fraction) * dtSeconds;
                crossingX = lerp(previous[0], state[0], fraction);
                crossingVx = lerp(previous[2], state[2], fraction);
                crossingVz = lerp(previous[3], state[3], fraction);
            }

            if (!Double.isNaN(crossingTime) && !Double.isNaN(nearRimHeight)) {
                double usableHalfSpan = usableHalfSpanMeters();
                double centerOffset = Math.abs(crossingX - targetDistanceMeters);
                double openingClearance = usableHalfSpan - centerOffset;
                double nearRimClearance = nearRimHeight - planeHeight;
                double entryAngle = Math.toDegrees(
                    Math.atan2(-crossingVz, Math.max(Math.abs(crossingVx), 1e-9))
                );
                boolean inside = centerOffset <= usableHalfSpan;
                boolean scoring = inside
                    && nearRimClearance >= ShotModelConstants.HUB_RIM_MARGIN_METERS
                    && entryAngle >= ShotModelConstants.MIN_ENTRY_ANGLE_DEGREES;
                return new EntryMetrics(
                    crossingTime,
                    entryAngle,
                    crossingX,
                    centerOffset,
                    openingClearance,
                    nearRimClearance,
                    inside,
                    scoring
                );
            }

            if (state[1] < 0.0 || state[0] > maxX) {
                break;
            }
        }
        return null;
    }

    private static void rk4Step(
        double[] state,
        double dt,
        double[] k1,
        double[] k2,
        double[] k3,
        double[] k4,
        double[] temporary
    ) {
        derivative(state, k1);
        addScaled(state, k1, 0.5 * dt, temporary);
        derivative(temporary, k2);
        addScaled(state, k2, 0.5 * dt, temporary);
        derivative(temporary, k3);
        addScaled(state, k3, dt, temporary);
        derivative(temporary, k4);

        for (int index = 0; index < state.length; index++) {
            state[index] += dt * (k1[index] + 2.0 * k2[index] + 2.0 * k3[index] + k4[index]) / 6.0;
        }
    }

    private static void derivative(double[] state, double[] result) {
        double vx = state[2];
        double vz = state[3];
        double omega = state[4];
        double relativeVx = vx - ShotModelConstants.WIND_X_METERS_PER_SECOND;
        double relativeVz = vz;
        double relativeSpeed = Math.hypot(relativeVx, relativeVz);
        double accelerationX = 0.0;
        double accelerationZ = -ShotModelConstants.GRAVITY_METERS_PER_SECOND_SQUARED;

        if (relativeSpeed > 1e-8) {
            double dragFactor =
                -DYNAMIC_ACCELERATION_FACTOR
                    * ShotModelConstants.DRAG_COEFFICIENT
                    * ShotModelConstants.DRAG_SCALE
                    * relativeSpeed;
            accelerationX += dragFactor * relativeVx;
            accelerationZ += dragFactor * relativeVz;

            double spinRatio = BALL_RADIUS_METERS * Math.abs(omega) / relativeSpeed;
            double liftCoefficient = Math.min(
                ShotModelConstants.MAX_LIFT_COEFFICIENT,
                ShotModelConstants.LIFT_SLOPE * spinRatio
            );
            double liftFactor =
                DYNAMIC_ACCELERATION_FACTOR
                    * liftCoefficient
                    * relativeSpeed
                    * Math.signum(omega);
            accelerationX += liftFactor * -relativeVz;
            accelerationZ += liftFactor * relativeVx;
        }

        result[0] = vx;
        result[1] = vz;
        result[2] = accelerationX;
        result[3] = accelerationZ;
        result[4] = -ShotModelConstants.SPIN_DECAY_PER_SECOND * omega;
    }

    private static void addScaled(double[] state, double[] derivative, double scale, double[] result) {
        for (int index = 0; index < state.length; index++) {
            result[index] = state[index] + derivative[index] * scale;
        }
    }

    private static double lerp(double start, double end, double fraction) {
        return start + fraction * (end - start);
    }

    private static double evaluateQuadratic(
        double distanceSquaredCoefficient,
        double distanceCoefficient,
        double constant,
        double value
    ) {
        return (distanceSquaredCoefficient * value + distanceCoefficient) * value + constant;
    }

    private static double clamp(double value, double minimum, double maximum) {
        return Math.max(minimum, Math.min(maximum, value));
    }
}
